---
name: Nicholas Tierney
position: "Research Fellow"
address: "Monash University, Australia"
www: njtierney.com
profilepic: "njtierney.png"
email: "nicholas.tierney@gmail.com"
twitter: nj_tierney
github: njtierney
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Constantly excited about #rstats"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
```

# Welcome

This is my resume, I'd like some jobs please.

# Education
```{r education}
edu <- rorcid::orcid_educations("0000-0003-1460-8722")
edu$`0000-0003-1460-8722`$`education-summary` %>%
  detailed_entries(
    what = `role-title`,
    when = glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"),
    with = organization.name,
    where = organization.address.city
  )
```

# R Packages
```{r rpkgs}
pkgsearch::ps("Tierney",size = 100) %>%
  filter(maintainer_name == "Nicholas Tierney") %>%
  brief_entries(
    what = title,
    when = lubridate::year(date),
    with = description
  )
```

# Selected talks
```{r talks}
tibble::tribble(
  ~name, ~event, ~location, ~year,
  "Empowering people with community, software, and peer review", "**RUCK: R Users Conference Korea (Invited Keynote speaker)**", "Seoul, Korea", 2018,
  "Now you see it?  Now you don’t?  The role of graphics in identifying MCMC convergence (Awarded Runner up Pitman Prize for Young Statistician)", "ISCB-ASC", "Melbourne, Australia", 2018,
  "Find the best locations for facilities using `maxcovr`", "UseR! 2018", "Brisbane, Australia", 2018
) %>%
  detailed_entries(
    what = name,
    when = year,
    with = event,
    where = location
  )
```

\endfirstpage

# Publications
```{r publications}
scholar::get_publications("o4eVsQEAAAAJ") %>%
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal,
    why = cites
  )
```
